### ISSUE TITLE
请问使用的是哪篇论文的方法？

### ISSUE THREAD

**Issue by ZhaiMen-Hub** [mpt0816/ContingencyPlanning#2]
如题

**Comment by mpt0816** [comment]
没有复现论文，只是根据contingency planning的理论，做的简单的demo

**Comment by ZhaiMen-Hub** [comment]
有什么学习contingency planning理论的材料推荐吗？
另外没理解错的话，看起来有点像很经典的Contingency Model Predictive Control的思路hh
[Contingency Model Predictive Control for Linear Time-Varying Systems - 知乎](https://zhuanlan.zhihu.com/p/631676428)
