### ISSUE TITLE
关于运行结果

### ISSUE THREAD

**Issue by chaiyanana** [mpt0816/ContingencyPlanning#3]
想请教一下，在cut-in概率为0是，Contingency 的有减速倾向。但是我感觉既然不会cut-in 那为什么还会有减速倾向？

**Comment by chaiyanana** [comment]
另外还是概率为0的图，在t=7秒时，Contingency和Obstacle出于同一个s点，是不是意味着发生了碰撞？

**Comment by mpt0816** [comment]
cut in概率为0时，对应的cut in情况下的trajectory不会有约束作用，并且不会对cost产生影响，其生成的轨迹是无效的。

**Comment by chaiyanana** [comment]
大佬留个联系方式，私底下交流交流

**Comment by chaiyanana** [comment]
我VX YN9381
